name: Build documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  INSTANCE: 'Writerside/hi'
  ARTIFACT: 'webHelpHI2-all.zip'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install WriterSide
        run: |
          wget https://path/to/writerside.zip  # Mettez ici le bon chemin pour télécharger WriterSide
          unzip writerside.zip -d /path/to/writerside  # Décompressez WriterSide dans le bon répertoire
          cd /path/to/writerside
          # Si WriterSide nécessite une installation ou un build supplémentaire, effectuez-le ici.

      - name: Build documentation using WriterSide
        run: |
          /path/to/writerside/writerside build # Exécutez la commande pour construire la documentation

      - name: Save artifact with build results
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: |
            /path/to/generated/docs/${{ env.ARTIFACT }}  # Chemin vers l'artefact généré
          retention-days: 7
